version: "3.8"
  mysqldb:
    container_name: mysql
    image: mysql/mysql-server:latest
    env_file:
      - .env
    environment:
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_HOST=%
    networks:
      - springmysql-net
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/my.cnf:ro
